# Optimizes images and creates a pull request following changes in a branch.
# A PR will be created if at least `minFiles` changed and the total size reduction is at least `minSize` megabytes.
#
# Note: The way the PR itself is made is a hack. Improving this having access to a functioning token.
# See: https://github.com/microsoft/azure-pipelines-tasks/issues/9754

parameters:
  minFiles: 1
  minSize: 0.0000001
  branchPrefix: image_optim
  resultFile: /tmp/result.md

jobs:
  - job: OptimizeImages
    condition: and(not(startswith(variables['Build.SourceBranch'], 'refs/heads/${{ parameters.branchPrefix }}/')),
                   not(startswith(variables['System.PullRequest.SourceBranch'], '${{ parameters.branchPrefix }}/')))
    strategy:
      maxParallel: 1
    continueOnError: true
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - checkout: self
      submodules: false
      persistCredentials: true

    - script: |
        brew install svgo gnu-sed
        gem install image_optim image_optim_pack
      displayName: 'Install dependencies'

    - script: |
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Doist/PipelinesTemplates/master/scripts/optimize-images.rb)" ${{ parameters.minFiles }} ${{ parameters.minSize }} > ${{ parameters.resultFile }}
        [ $? -eq 0 ] && echo "##vso[task.setvariable variable=OPTIMIZED]true" && cat ${{ parameters.resultFile }}
      timeoutInMinutes: 120
      continueOnError: true
      displayName: 'Optimize images'

    - script: |
        result=$(cat ${{ parameters.resultFile }}) && \
        head="${{ parameters.branchPrefix }}/$BUILD_SOURCEVERSION" && \
        git checkout -b "$head" && \
        git add -u && \
        git commit -a -m "Optimize images (lossless)" -m "$result" && \
        git push origin "$head" --force-with-lease && \

        token=$(git config --get http.$(Build.Repository.Uri).extraheader | cut -d' ' -f3 | base64 --decode | cut -d':' -f2) && \
        base="${BUILD_SOURCEBRANCH/\/refs\/heads\//}" && \
        repo="${BUILD_REPOSITORY_URI##*/}" && \
        owner_url="${BUILD_REPOSITORY_URI%/*}" && \
        owner_repo="${owner_url##*/}/$repo" && \
        result=$(echo "$result" | gsed -z 's/\n/\\n/g') && \
        curl -v \
          -H "Authorization: token $token" \
          -H "Accept: application/vnd.github.machine-man-preview+json" \
          -d "{\"title\":\"Optimize images (lossless)\", \"head\":\"$head\", \"base\":\"$base\", \"body\":\"$result\", \"maintainer_can_modify\":true}" \
          "https://api.github.com/repos/$owner_repo/pulls"
      condition: eq(variables.OPTIMIZED, 'true')
      displayName: 'Create pull request'
