# Pushes string files to Transifex.

parameters:
- name: source_file_pattern
  type: string
  default: ".*/res/values/strings"
- name: transifex_token
  type: string
- name: transifex_client_version
  type: string
  default: "0.13.11"
- name: twist_install_id
  type: string
- name: twist_install_token
  type: string

jobs:
  - job: TransifexPush
    pool:
      vmImage: 'macOS-10.15'
    timeoutInMinutes: 20
    steps:
    - checkout: self
      submodules: false
      persistCredentials: true
    - script: |
        if [ `git log -m -1 --name-only --pretty="format:" | grep "${{ parameters.source_file_pattern }}" | wc -l` -gt 0 ]; then
          pip install transifex-client==${{ parameters.transifex_client_version }}
          tx push -s
        fi;
      env:
        TX_TOKEN: ${{ parameters.transifex_token }}
      failOnStderr: true
      displayName: 'Push strings to Transifex'
    - script: |
        curl --header "Content-Type: application/json" \
        --request POST \
        --data '{"content":"❌ Failed to push strings from [this commit]('"$BUILD_REPOSITORY_URI"'/commit/'"$BUILD_SOURCEVERSION"')."}' \
        "https://twist.com/api/v3/integration_incoming/post_data?install_id=${{ parameters.twist_install_id }}&install_token=${{ parameters.twist_install_token }}"
      condition: failed()
      displayName: 'Post push status to Twist'
