# Optimizes images and creates a pull request following changes in a branch.
# See each parameter's documentation.
#
# Note: The way the PR itself is made is a hack. Improving this having access to a functioning token.
# See: https://github.com/microsoft/azure-pipelines-tasks/issues/9754

parameters:
  # How many files must change for a PR to be created.
  minFiles: 1
  # How many bytes must be reduced for a PR to be created.
  minSize: 1
  # Branch prefix to use, eg. "image_optim/<source-branch>".
  branchPrefix: image_optim
  # List of paths to exclude, eg. ['store/', 'original\ mockups/'].
  # Each path must be single-quoted ('path'), and its spaces escaped ('original\ path').
  excludePaths: []

jobs:
  - job: OptimizeImages
    condition: and(not(startswith(variables['Build.SourceBranch'], 'refs/heads/${{ parameters.branchPrefix }}/')),
                   not(startswith(variables['System.PullRequest.SourceBranch'], '${{ parameters.branchPrefix }}/')))
    strategy:
      maxParallel: 1
    continueOnError: true
    pool:
      vmImage: 'macOS-10.15'
    steps:
    - checkout: self
      submodules: false
      persistCredentials: true

    - script: |
        brew install svgo gnu-sed
        gem install image_optim image_optim_pack
      displayName: 'Install dependencies'

    - script: |
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Doist/PipelinesTemplates/master/scripts/optimize-images.rb)" \
        --min-files ${{ parameters.minFiles }} --min-size ${{ parameters.minSize }} \
        --exclude ${{ join(' ', parameters.excludePaths) }} > /tmp/result.md
        [ -s /tmp/result.md ] && echo "##vso[task.setvariable variable=OPTIMIZED]true" && cat /tmp/result.md || exit 0
      timeoutInMinutes: 120
      displayName: 'Optimize images'

    - script: |
        head="${{ parameters.branchPrefix }}/$BUILD_SOURCEBRANCH" && \
        git checkout -b "$head" && \
        git add -u && \
        git commit -a -m "Optimize images (lossless)" && \
        git push origin "$head" --force && \

        result=$(cat /tmp/result.md | gsed -z 's/\n/\\n/g') && \
        token=$(git config --get http.$(Build.Repository.Uri).extraheader | cut -d' ' -f3 | base64 --decode | cut -d':' -f2) && \
        base="${BUILD_SOURCEBRANCH/\/refs\/heads\//}" && \
        repo="${BUILD_REPOSITORY_URI##*/}" && \
        owner_url="${BUILD_REPOSITORY_URI%/*}" && \
        owner_repo="${owner_url##*/}/$repo" && \
        curl -v \
          -H "Authorization: token $token" \
          -H "Accept: application/vnd.github.machine-man-preview+json" \
          -d "{\"title\":\"Optimize images (lossless)\", \"head\":\"$head\", \"base\":\"$base\", \"body\":\"$result\", \"maintainer_can_modify\":true}" \
          "https://api.github.com/repos/$owner_repo/pulls"
      condition: eq(variables.OPTIMIZED, 'true')
      displayName: 'Create pull request'
